// Generated by scripts/generate_native_exec.py. Do not edit by hand.
#pragma once

#include <array>
#include <cstddef>
#include <span>
#include <string_view>

namespace aemcp::native {

enum class PrimitiveMutability { kRead, kWrite };
enum class PrimitiveValueKind { kJson, kCompositionHandle, kLayerHandle, kPropertyHandle };

struct NativeReferenceArgument {
  std::string_view name;
  PrimitiveValueKind kind;
  bool required;
};

struct NativePrimitiveDescriptor {
  std::string_view id;
  PrimitiveMutability mutability;
  std::string_view required_suite;
  std::string_view input_schema_json;
  std::span<const NativeReferenceArgument> reference_arguments;
  std::string_view result_schema_json;
  std::string_view summary;
  std::string_view executor_symbol;
  PrimitiveValueKind result_kind;
  bool exportable;
};

inline constexpr std::size_t kNativePrimitiveCount = 23;
inline constexpr std::string_view kNativeExecRegistryDigest = "ac1353a16a045105ea189038ee707bdcf35b5d146056d7c1757b2bdb8acfdbd7";
inline constexpr std::array<NativeReferenceArgument, 0> kNativePrimitiveReferenceArguments0{{
}};

inline constexpr std::array<NativeReferenceArgument, 1> kNativePrimitiveReferenceArguments1{{
    NativeReferenceArgument{"composition", PrimitiveValueKind::kCompositionHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 1> kNativePrimitiveReferenceArguments2{{
    NativeReferenceArgument{"layer", PrimitiveValueKind::kLayerHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 0> kNativePrimitiveReferenceArguments3{{
}};

inline constexpr std::array<NativeReferenceArgument, 1> kNativePrimitiveReferenceArguments4{{
    NativeReferenceArgument{"composition", PrimitiveValueKind::kCompositionHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 1> kNativePrimitiveReferenceArguments5{{
    NativeReferenceArgument{"composition", PrimitiveValueKind::kCompositionHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 1> kNativePrimitiveReferenceArguments6{{
    NativeReferenceArgument{"composition", PrimitiveValueKind::kCompositionHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 1> kNativePrimitiveReferenceArguments7{{
    NativeReferenceArgument{"composition", PrimitiveValueKind::kCompositionHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 1> kNativePrimitiveReferenceArguments8{{
    NativeReferenceArgument{"composition", PrimitiveValueKind::kCompositionHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 1> kNativePrimitiveReferenceArguments9{{
    NativeReferenceArgument{"composition", PrimitiveValueKind::kCompositionHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 1> kNativePrimitiveReferenceArguments10{{
    NativeReferenceArgument{"composition", PrimitiveValueKind::kCompositionHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 1> kNativePrimitiveReferenceArguments11{{
    NativeReferenceArgument{"composition", PrimitiveValueKind::kCompositionHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 1> kNativePrimitiveReferenceArguments12{{
    NativeReferenceArgument{"composition", PrimitiveValueKind::kCompositionHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 2> kNativePrimitiveReferenceArguments13{{
    NativeReferenceArgument{"layer", PrimitiveValueKind::kLayerHandle, true},
    NativeReferenceArgument{"parentProperty", PrimitiveValueKind::kPropertyHandle, false},
}};

inline constexpr std::array<NativeReferenceArgument, 1> kNativePrimitiveReferenceArguments14{{
    NativeReferenceArgument{"property", PrimitiveValueKind::kPropertyHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 2> kNativePrimitiveReferenceArguments15{{
    NativeReferenceArgument{"layer", PrimitiveValueKind::kLayerHandle, true},
    NativeReferenceArgument{"property", PrimitiveValueKind::kPropertyHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 1> kNativePrimitiveReferenceArguments16{{
    NativeReferenceArgument{"property", PrimitiveValueKind::kPropertyHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 2> kNativePrimitiveReferenceArguments17{{
    NativeReferenceArgument{"layer", PrimitiveValueKind::kLayerHandle, true},
    NativeReferenceArgument{"property", PrimitiveValueKind::kPropertyHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 2> kNativePrimitiveReferenceArguments18{{
    NativeReferenceArgument{"layer", PrimitiveValueKind::kLayerHandle, true},
    NativeReferenceArgument{"property", PrimitiveValueKind::kPropertyHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 2> kNativePrimitiveReferenceArguments19{{
    NativeReferenceArgument{"layer", PrimitiveValueKind::kLayerHandle, true},
    NativeReferenceArgument{"property", PrimitiveValueKind::kPropertyHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 2> kNativePrimitiveReferenceArguments20{{
    NativeReferenceArgument{"layer", PrimitiveValueKind::kLayerHandle, true},
    NativeReferenceArgument{"property", PrimitiveValueKind::kPropertyHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 2> kNativePrimitiveReferenceArguments21{{
    NativeReferenceArgument{"layer", PrimitiveValueKind::kLayerHandle, true},
    NativeReferenceArgument{"property", PrimitiveValueKind::kPropertyHandle, true},
}};

inline constexpr std::array<NativeReferenceArgument, 2> kNativePrimitiveReferenceArguments22{{
    NativeReferenceArgument{"layer", PrimitiveValueKind::kLayerHandle, true},
    NativeReferenceArgument{"property", PrimitiveValueKind::kPropertyHandle, true},
}};

inline constexpr std::array<NativePrimitiveDescriptor, kNativePrimitiveCount>
    kNativePrimitiveRegistry{{
    NativePrimitiveDescriptor{
        "composition.resolve",
        PrimitiveMutability::kRead,
        "AEGP_CompSuite12",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"locator":{"$ref":"aegp-rpc.schema.json#/$defs/compositionLocator"}},"required":["locator"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments0},
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"exportable":{"const":false},"handle":{"additionalProperties":false,"properties":{"kind":{"const":"composition"},"value":{"minimum":1,"type":"integer"}},"required":["kind","value"],"type":"object"}},"required":["handle","exportable"],"type":"object"})NATIVEEXEC",
        R"NATIVEEXEC(Read composition.resolve.)NATIVEEXEC",
        "execute_composition_resolve",
        PrimitiveValueKind::kCompositionHandle,
        false,
    },
    NativePrimitiveDescriptor{
        "layer.resolve",
        PrimitiveMutability::kRead,
        "AEGP_LayerSuite9",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"locator":{"$ref":"aegp-rpc.schema.json#/$defs/layerLocator"}},"required":["locator"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments1},
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"exportable":{"const":false},"handle":{"additionalProperties":false,"properties":{"kind":{"const":"layer"},"value":{"minimum":1,"type":"integer"}},"required":["kind","value"],"type":"object"}},"required":["handle","exportable"],"type":"object"})NATIVEEXEC",
        R"NATIVEEXEC(Read layer.resolve.)NATIVEEXEC",
        "execute_layer_resolve",
        PrimitiveValueKind::kLayerHandle,
        false,
    },
    NativePrimitiveDescriptor{
        "property.resolve",
        PrimitiveMutability::kRead,
        "AEGP_StreamSuite5",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"locator":{"$ref":"aegp-rpc.schema.json#/$defs/streamLocator"}},"required":["locator"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments2},
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"exportable":{"const":false},"handle":{"additionalProperties":false,"properties":{"kind":{"const":"property"},"value":{"minimum":1,"type":"integer"}},"required":["kind","value"],"type":"object"}},"required":["handle","exportable"],"type":"object"})NATIVEEXEC",
        R"NATIVEEXEC(Read property.resolve.)NATIVEEXEC",
        "execute_property_resolve",
        PrimitiveValueKind::kPropertyHandle,
        false,
    },
    NativePrimitiveDescriptor{
        "project.items.list",
        PrimitiveMutability::kRead,
        "AEGP_ProjSuite6",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"limit":{"maximum":50,"minimum":1,"type":"integer"},"offset":{"$ref":"aegp-rpc.schema.json#/$defs/pageOffset"},"projectLocator":{"$ref":"aegp-rpc.schema.json#/$defs/projectLocator"}},"required":["offset","limit"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments3},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/projectItemsListValue"})NATIVEEXEC",
        R"NATIVEEXEC(Read project.items.list.)NATIVEEXEC",
        "execute_project_items_list",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "composition.layers.list",
        PrimitiveMutability::kRead,
        "AEGP_CompSuite12",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"limit":{"maximum":25,"minimum":1,"type":"integer"},"offset":{"$ref":"aegp-rpc.schema.json#/$defs/pageOffset"}},"required":["offset","limit"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments4},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/compositionLayersListValue"})NATIVEEXEC",
        R"NATIVEEXEC(Read composition.layers.list.)NATIVEEXEC",
        "execute_composition_layers_list",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "composition.selectedLayers.list",
        PrimitiveMutability::kRead,
        "AEGP_CompSuite12",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"limit":{"maximum":25,"minimum":1,"type":"integer"},"offset":{"$ref":"aegp-rpc.schema.json#/$defs/pageOffset"}},"required":["offset","limit"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments5},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/compositionSelectedLayersListInvokeResult"})NATIVEEXEC",
        R"NATIVEEXEC(Read composition.selectedLayers.list.)NATIVEEXEC",
        "execute_composition_selectedLayers_list",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "composition.time.read",
        PrimitiveMutability::kRead,
        "AEGP_CompSuite12",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{},"required":[],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments6},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/compositionTimeReadValue"})NATIVEEXEC",
        R"NATIVEEXEC(Read composition.time.read.)NATIVEEXEC",
        "execute_composition_time_read",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "composition.time.set",
        PrimitiveMutability::kWrite,
        "AEGP_CompSuite12",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"targetTime":{"additionalProperties":false,"properties":{"scale":{"maximum":4294967295,"minimum":1,"type":"integer"},"value":{"maximum":2147483647,"minimum":-2147483648,"type":"integer"}},"required":["value","scale"],"type":"object"}},"required":["targetTime"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments7},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/compositionTimeSetInvokeResult"})NATIVEEXEC",
        R"NATIVEEXEC(Write composition.time.set.)NATIVEEXEC",
        "execute_composition_time_set",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "composition.settings.read",
        PrimitiveMutability::kRead,
        "AEGP_CompSuite12",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{},"required":[],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments8},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/compositionSettingsReadValue"})NATIVEEXEC",
        R"NATIVEEXEC(Read composition.settings.read.)NATIVEEXEC",
        "execute_composition_settings_read",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "composition.duration.set",
        PrimitiveMutability::kWrite,
        "AEGP_CompSuite12",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"duration":{"additionalProperties":false,"properties":{"scale":{"maximum":4294967295,"minimum":1,"type":"integer"},"value":{"maximum":2147483647,"minimum":1,"type":"integer"}},"required":["value","scale"],"type":"object"}},"required":["duration"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments9},
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"evidence":{"$ref":"aegp-rpc.schema.json#/$defs/executionEvidence"},"value":{"$ref":"aegp-rpc.schema.json#/$defs/tsmGeneratedAeCompositionDurationSetValue"}},"required":["value","evidence"],"type":"object"})NATIVEEXEC",
        R"NATIVEEXEC(Write composition.duration.set.)NATIVEEXEC",
        "execute_composition_duration_set",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "composition.frameRate.set",
        PrimitiveMutability::kWrite,
        "AEGP_CompSuite12",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"frameRate":{"additionalProperties":false,"properties":{"denominator":{"maximum":2147483647,"minimum":1,"type":"integer"},"numerator":{"maximum":2147483647,"minimum":1,"type":"integer"}},"required":["numerator","denominator"],"type":"object"}},"required":["frameRate"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments10},
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"evidence":{"$ref":"aegp-rpc.schema.json#/$defs/executionEvidence"},"value":{"$ref":"aegp-rpc.schema.json#/$defs/tsmGeneratedAeCompositionFrameRateSetValue"}},"required":["value","evidence"],"type":"object"})NATIVEEXEC",
        R"NATIVEEXEC(Write composition.frameRate.set.)NATIVEEXEC",
        "execute_composition_frameRate_set",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "composition.pixelAspectRatio.set",
        PrimitiveMutability::kWrite,
        "AEGP_CompSuite12",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"pixelAspectRatio":{"additionalProperties":false,"properties":{"denominator":{"maximum":2147483647,"minimum":1,"type":"integer"},"numerator":{"maximum":2147483647,"minimum":1,"type":"integer"}},"required":["numerator","denominator"],"type":"object"}},"required":["pixelAspectRatio"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments11},
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"evidence":{"$ref":"aegp-rpc.schema.json#/$defs/executionEvidence"},"value":{"$ref":"aegp-rpc.schema.json#/$defs/tsmGeneratedAeCompositionPixelAspectRatioSetValue"}},"required":["value","evidence"],"type":"object"})NATIVEEXEC",
        R"NATIVEEXEC(Write composition.pixelAspectRatio.set.)NATIVEEXEC",
        "execute_composition_pixelAspectRatio_set",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "composition.displayStartTime.set",
        PrimitiveMutability::kWrite,
        "AEGP_CompSuite12",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"displayStartTime":{"additionalProperties":false,"properties":{"scale":{"maximum":4294967295,"minimum":1,"type":"integer"},"value":{"maximum":2147483647,"minimum":-2147483648,"type":"integer"}},"required":["value","scale"],"type":"object"}},"required":["displayStartTime"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments12},
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"evidence":{"$ref":"aegp-rpc.schema.json#/$defs/executionEvidence"},"value":{"$ref":"aegp-rpc.schema.json#/$defs/tsmGeneratedAeCompositionDisplayStartTimeSetValue"}},"required":["value","evidence"],"type":"object"})NATIVEEXEC",
        R"NATIVEEXEC(Write composition.displayStartTime.set.)NATIVEEXEC",
        "execute_composition_displayStartTime_set",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "layer.properties.list",
        PrimitiveMutability::kRead,
        "AEGP_LayerSuite9",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"limit":{"maximum":25,"minimum":1,"type":"integer"},"offset":{"$ref":"aegp-rpc.schema.json#/$defs/pageOffset"}},"required":["offset","limit"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments13},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/layerPropertiesListValue"})NATIVEEXEC",
        R"NATIVEEXEC(Read layer.properties.list.)NATIVEEXEC",
        "execute_layer_properties_list",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "property.keyframes.list",
        PrimitiveMutability::kRead,
        "AEGP_StreamSuite5",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"limit":{"maximum":25,"minimum":1,"type":"integer"},"offset":{"$ref":"aegp-rpc.schema.json#/$defs/pageOffset"}},"required":["offset","limit"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments14},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/layerPropertyKeyframesListValue"})NATIVEEXEC",
        R"NATIVEEXEC(Read property.keyframes.list.)NATIVEEXEC",
        "execute_property_keyframes_list",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "property.value.set",
        PrimitiveMutability::kWrite,
        "AEGP_StreamSuite5",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"value":{"$ref":"aegp-rpc.schema.json#/$defs/layerPropertyPrimitiveValue"}},"required":["value"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments15},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/layerPropertySetInvokeResult"})NATIVEEXEC",
        R"NATIVEEXEC(Write property.value.set.)NATIVEEXEC",
        "execute_property_value_set",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "property.keyframe.details.read",
        PrimitiveMutability::kRead,
        "AEGP_StreamSuite5",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"}},"required":["time"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments16},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/keyframeDetailsValue"})NATIVEEXEC",
        R"NATIVEEXEC(Read property.keyframe.details.read.)NATIVEEXEC",
        "execute_property_keyframe_details_read",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "property.keyframe.add",
        PrimitiveMutability::kWrite,
        "AEGP_StreamSuite5",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"},"value":{"$ref":"aegp-rpc.schema.json#/$defs/layerPropertyPrimitiveValue"}},"required":["time","value"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments17},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/keyframeAddInvokeResult"})NATIVEEXEC",
        R"NATIVEEXEC(Write property.keyframe.add.)NATIVEEXEC",
        "execute_property_keyframe_add",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "property.keyframe.value.set",
        PrimitiveMutability::kWrite,
        "AEGP_StreamSuite5",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"},"value":{"$ref":"aegp-rpc.schema.json#/$defs/layerPropertyPrimitiveValue"}},"required":["time","value"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments18},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/keyframeValueSetInvokeResult"})NATIVEEXEC",
        R"NATIVEEXEC(Write property.keyframe.value.set.)NATIVEEXEC",
        "execute_property_keyframe_value_set",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "property.keyframe.interpolation.set",
        PrimitiveMutability::kWrite,
        "AEGP_StreamSuite5",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"inInterpolation":{"enum":["linear","bezier","hold"]},"outInterpolation":{"enum":["linear","bezier","hold"]},"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"}},"required":["time","inInterpolation","outInterpolation"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments19},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/keyframeInterpolationSetInvokeResult"})NATIVEEXEC",
        R"NATIVEEXEC(Write property.keyframe.interpolation.set.)NATIVEEXEC",
        "execute_property_keyframe_interpolation_set",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "property.keyframe.temporalEase.set",
        PrimitiveMutability::kWrite,
        "AEGP_StreamSuite5",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"dimensions":{"items":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeEaseDimension"},"maxItems":4,"minItems":1,"type":"array"},"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"}},"required":["time","dimensions"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments20},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/keyframeTemporalEaseSetInvokeResult"})NATIVEEXEC",
        R"NATIVEEXEC(Write property.keyframe.temporalEase.set.)NATIVEEXEC",
        "execute_property_keyframe_temporalEase_set",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "property.keyframe.behavior.set",
        PrimitiveMutability::kWrite,
        "AEGP_StreamSuite5",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"behavior":{"enum":["temporal-continuous","temporal-auto-bezier","spatial-continuous","spatial-auto-bezier","roving"]},"enabled":{"type":"boolean"},"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"}},"required":["time","behavior","enabled"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments21},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/keyframeBehaviorSetInvokeResult"})NATIVEEXEC",
        R"NATIVEEXEC(Write property.keyframe.behavior.set.)NATIVEEXEC",
        "execute_property_keyframe_behavior_set",
        PrimitiveValueKind::kJson,
        true,
    },
    NativePrimitiveDescriptor{
        "property.keyframe.delete",
        PrimitiveMutability::kWrite,
        "AEGP_StreamSuite5",
        R"NATIVEEXEC({"additionalProperties":false,"properties":{"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"}},"required":["time"],"type":"object"})NATIVEEXEC",
        std::span<const NativeReferenceArgument>{kNativePrimitiveReferenceArguments22},
        R"NATIVEEXEC({"$ref":"aegp-rpc.schema.json#/$defs/keyframeDeleteInvokeResult"})NATIVEEXEC",
        R"NATIVEEXEC(Write property.keyframe.delete.)NATIVEEXEC",
        "execute_property_keyframe_delete",
        PrimitiveValueKind::kJson,
        true,
    },
}};

inline constexpr std::array<std::string_view, kNativePrimitiveCount> kNativePrimitiveSummaryJson{{
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"composition.resolve","idempotency":"idempotent","mutability":"read-only","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read composition.resolve.","undo":"not-applicable","valueKind":"CompositionHandle","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"layer.resolve","idempotency":"idempotent","mutability":"read-only","preconditions":["AEGP_LayerSuite9 must be available."],"requiredSuite":"AEGP_LayerSuite9","risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read layer.resolve.","undo":"not-applicable","valueKind":"LayerHandle","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"property.resolve","idempotency":"idempotent","mutability":"read-only","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read property.resolve.","undo":"not-applicable","valueKind":"PropertyHandle","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"project.items.list","idempotency":"idempotent","mutability":"read-only","preconditions":["AEGP_ProjSuite6 must be available."],"requiredSuite":"AEGP_ProjSuite6","risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read project.items.list.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"composition.layers.list","idempotency":"idempotent","mutability":"read-only","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read composition.layers.list.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"composition.selectedLayers.list","idempotency":"idempotent","mutability":"read-only","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read composition.selectedLayers.list.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"composition.time.read","idempotency":"idempotent","mutability":"read-only","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read composition.time.read.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"composition.time.set","idempotency":"idempotency-key","mutability":"mutating","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write composition.time.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"composition.settings.read","idempotency":"idempotent","mutability":"read-only","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read composition.settings.read.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"composition.duration.set","idempotency":"idempotency-key","mutability":"mutating","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write composition.duration.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"composition.frameRate.set","idempotency":"idempotency-key","mutability":"mutating","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write composition.frameRate.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"composition.pixelAspectRatio.set","idempotency":"idempotency-key","mutability":"mutating","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write composition.pixelAspectRatio.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"composition.displayStartTime.set","idempotency":"idempotency-key","mutability":"mutating","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write composition.displayStartTime.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"layer.properties.list","idempotency":"idempotent","mutability":"read-only","preconditions":["AEGP_LayerSuite9 must be available."],"requiredSuite":"AEGP_LayerSuite9","risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read layer.properties.list.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"property.keyframes.list","idempotency":"idempotent","mutability":"read-only","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read property.keyframes.list.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"property.value.set","idempotency":"idempotency-key","mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.value.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"property.keyframe.details.read","idempotency":"idempotent","mutability":"read-only","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read property.keyframe.details.read.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"property.keyframe.add","idempotency":"idempotency-key","mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.keyframe.add.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"property.keyframe.value.set","idempotency":"idempotency-key","mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.keyframe.value.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"property.keyframe.interpolation.set","idempotency":"idempotency-key","mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.keyframe.interpolation.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"property.keyframe.temporalEase.set","idempotency":"idempotency-key","mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.keyframe.temporalEase.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"property.keyframe.behavior.set","idempotency":"idempotency-key","mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.keyframe.behavior.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"detail":"summary","id":"property.keyframe.delete","idempotency":"idempotency-key","mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.keyframe.delete.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
}};

inline constexpr std::array<std::string_view, kNativePrimitiveCount> kNativePrimitiveFullJson{{
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"bedb1cb0f0f0975d070328ded85b0206e10c94929f8c3756862395722e05a7ea","detail":"full","id":"composition.resolve","idempotency":"idempotent","inputSchema":{"additionalProperties":false,"properties":{"locator":{"$ref":"aegp-rpc.schema.json#/$defs/compositionLocator"}},"required":["locator"],"type":"object"},"mutability":"read-only","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","resultSchema":{"additionalProperties":false,"properties":{"exportable":{"const":false},"handle":{"additionalProperties":false,"properties":{"kind":{"const":"composition"},"value":{"minimum":1,"type":"integer"}},"required":["kind","value"],"type":"object"}},"required":["handle","exportable"],"type":"object"},"risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read composition.resolve.","undo":"not-applicable","valueKind":"CompositionHandle","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"7deebcae2527ae8fc22afa2d7398781144690b774e294b4b7b04c1bf4be24cdf","detail":"full","id":"layer.resolve","idempotency":"idempotent","inputSchema":{"additionalProperties":false,"properties":{"locator":{"$ref":"aegp-rpc.schema.json#/$defs/layerLocator"}},"required":["locator"],"type":"object"},"mutability":"read-only","preconditions":["AEGP_LayerSuite9 must be available."],"requiredSuite":"AEGP_LayerSuite9","resultSchema":{"additionalProperties":false,"properties":{"exportable":{"const":false},"handle":{"additionalProperties":false,"properties":{"kind":{"const":"layer"},"value":{"minimum":1,"type":"integer"}},"required":["kind","value"],"type":"object"}},"required":["handle","exportable"],"type":"object"},"risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read layer.resolve.","undo":"not-applicable","valueKind":"LayerHandle","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"089dbacfc20ef6638fb85ab98f45442772c1b9251282910cb2f3def0a9d46571","detail":"full","id":"property.resolve","idempotency":"idempotent","inputSchema":{"additionalProperties":false,"properties":{"locator":{"$ref":"aegp-rpc.schema.json#/$defs/streamLocator"}},"required":["locator"],"type":"object"},"mutability":"read-only","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","resultSchema":{"additionalProperties":false,"properties":{"exportable":{"const":false},"handle":{"additionalProperties":false,"properties":{"kind":{"const":"property"},"value":{"minimum":1,"type":"integer"}},"required":["kind","value"],"type":"object"}},"required":["handle","exportable"],"type":"object"},"risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read property.resolve.","undo":"not-applicable","valueKind":"PropertyHandle","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"bd2695a9eb0b09fcd8bf8284dc3f86fb44b7dd274b2e3c40b5d1686432831c46","detail":"full","id":"project.items.list","idempotency":"idempotent","inputSchema":{"additionalProperties":false,"properties":{"limit":{"maximum":50,"minimum":1,"type":"integer"},"offset":{"$ref":"aegp-rpc.schema.json#/$defs/pageOffset"},"projectLocator":{"$ref":"aegp-rpc.schema.json#/$defs/projectLocator"}},"required":["offset","limit"],"type":"object"},"mutability":"read-only","preconditions":["AEGP_ProjSuite6 must be available."],"requiredSuite":"AEGP_ProjSuite6","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/projectItemsListValue"},"risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read project.items.list.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"d741de7107adfec5c8560ac721a68a980f2dda388162c6b7f6983baa74f3034c","detail":"full","id":"composition.layers.list","idempotency":"idempotent","inputSchema":{"additionalProperties":false,"properties":{"limit":{"maximum":25,"minimum":1,"type":"integer"},"offset":{"$ref":"aegp-rpc.schema.json#/$defs/pageOffset"}},"required":["offset","limit"],"type":"object"},"mutability":"read-only","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/compositionLayersListValue"},"risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read composition.layers.list.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"971107b295c6b0955693034292e707d87020b789e30be21022787e5756228072","detail":"full","id":"composition.selectedLayers.list","idempotency":"idempotent","inputSchema":{"additionalProperties":false,"properties":{"limit":{"maximum":25,"minimum":1,"type":"integer"},"offset":{"$ref":"aegp-rpc.schema.json#/$defs/pageOffset"}},"required":["offset","limit"],"type":"object"},"mutability":"read-only","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/compositionSelectedLayersListInvokeResult"},"risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read composition.selectedLayers.list.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"b68e454a203d6cb2a542224661219ad810335dc2eee1ea3a1985e17883836eb2","detail":"full","id":"composition.time.read","idempotency":"idempotent","inputSchema":{"additionalProperties":false,"properties":{},"required":[],"type":"object"},"mutability":"read-only","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/compositionTimeReadValue"},"risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read composition.time.read.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"134a1392c886f4225df74e82fc1ed5419153ec29c7974c9e6f0d6d871027b370","detail":"full","id":"composition.time.set","idempotency":"idempotency-key","inputSchema":{"additionalProperties":false,"properties":{"targetTime":{"additionalProperties":false,"properties":{"scale":{"maximum":4294967295,"minimum":1,"type":"integer"},"value":{"maximum":2147483647,"minimum":-2147483648,"type":"integer"}},"required":["value","scale"],"type":"object"}},"required":["targetTime"],"type":"object"},"mutability":"mutating","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/compositionTimeSetInvokeResult"},"risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write composition.time.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"fa019292708c3492259971a5959d336e122f4056d87363ae500b66a1147bf9b5","detail":"full","id":"composition.settings.read","idempotency":"idempotent","inputSchema":{"additionalProperties":false,"properties":{},"required":[],"type":"object"},"mutability":"read-only","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/compositionSettingsReadValue"},"risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read composition.settings.read.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"b14d0ddfcbe108225e7944a0db25cbaf77064792d12c34b757ba177b4e2d7254","detail":"full","id":"composition.duration.set","idempotency":"idempotency-key","inputSchema":{"additionalProperties":false,"properties":{"duration":{"additionalProperties":false,"properties":{"scale":{"maximum":4294967295,"minimum":1,"type":"integer"},"value":{"maximum":2147483647,"minimum":1,"type":"integer"}},"required":["value","scale"],"type":"object"}},"required":["duration"],"type":"object"},"mutability":"mutating","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","resultSchema":{"additionalProperties":false,"properties":{"evidence":{"$ref":"aegp-rpc.schema.json#/$defs/executionEvidence"},"value":{"$ref":"aegp-rpc.schema.json#/$defs/tsmGeneratedAeCompositionDurationSetValue"}},"required":["value","evidence"],"type":"object"},"risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write composition.duration.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"d43da388606a16143d06532a3a1bffe73745f0bc16ae8732e2d7a3d7a73b62cd","detail":"full","id":"composition.frameRate.set","idempotency":"idempotency-key","inputSchema":{"additionalProperties":false,"properties":{"frameRate":{"additionalProperties":false,"properties":{"denominator":{"maximum":2147483647,"minimum":1,"type":"integer"},"numerator":{"maximum":2147483647,"minimum":1,"type":"integer"}},"required":["numerator","denominator"],"type":"object"}},"required":["frameRate"],"type":"object"},"mutability":"mutating","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","resultSchema":{"additionalProperties":false,"properties":{"evidence":{"$ref":"aegp-rpc.schema.json#/$defs/executionEvidence"},"value":{"$ref":"aegp-rpc.schema.json#/$defs/tsmGeneratedAeCompositionFrameRateSetValue"}},"required":["value","evidence"],"type":"object"},"risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write composition.frameRate.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"badc62f7fc0f0f9bc6f4b9f196535bf86b8b5cd3bffc71cdc1f3d840673916c4","detail":"full","id":"composition.pixelAspectRatio.set","idempotency":"idempotency-key","inputSchema":{"additionalProperties":false,"properties":{"pixelAspectRatio":{"additionalProperties":false,"properties":{"denominator":{"maximum":2147483647,"minimum":1,"type":"integer"},"numerator":{"maximum":2147483647,"minimum":1,"type":"integer"}},"required":["numerator","denominator"],"type":"object"}},"required":["pixelAspectRatio"],"type":"object"},"mutability":"mutating","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","resultSchema":{"additionalProperties":false,"properties":{"evidence":{"$ref":"aegp-rpc.schema.json#/$defs/executionEvidence"},"value":{"$ref":"aegp-rpc.schema.json#/$defs/tsmGeneratedAeCompositionPixelAspectRatioSetValue"}},"required":["value","evidence"],"type":"object"},"risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write composition.pixelAspectRatio.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"e3393749544fe2ebbd56d0d4a135e866c79250e12cb3f79ff6bdac02414d5b6e","detail":"full","id":"composition.displayStartTime.set","idempotency":"idempotency-key","inputSchema":{"additionalProperties":false,"properties":{"displayStartTime":{"additionalProperties":false,"properties":{"scale":{"maximum":4294967295,"minimum":1,"type":"integer"},"value":{"maximum":2147483647,"minimum":-2147483648,"type":"integer"}},"required":["value","scale"],"type":"object"}},"required":["displayStartTime"],"type":"object"},"mutability":"mutating","preconditions":["AEGP_CompSuite12 must be available."],"requiredSuite":"AEGP_CompSuite12","resultSchema":{"additionalProperties":false,"properties":{"evidence":{"$ref":"aegp-rpc.schema.json#/$defs/executionEvidence"},"value":{"$ref":"aegp-rpc.schema.json#/$defs/tsmGeneratedAeCompositionDisplayStartTimeSetValue"}},"required":["value","evidence"],"type":"object"},"risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write composition.displayStartTime.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"051e745c3df7a1135f2559c0aad052bfb0567f02d35925b006de80b5d3b999a3","detail":"full","id":"layer.properties.list","idempotency":"idempotent","inputSchema":{"additionalProperties":false,"properties":{"limit":{"maximum":25,"minimum":1,"type":"integer"},"offset":{"$ref":"aegp-rpc.schema.json#/$defs/pageOffset"}},"required":["offset","limit"],"type":"object"},"mutability":"read-only","preconditions":["AEGP_LayerSuite9 must be available."],"requiredSuite":"AEGP_LayerSuite9","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/layerPropertiesListValue"},"risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read layer.properties.list.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"e9f84f6a282734e76dbba79edeb25b9d4b25d40e4169541a782fa28c9845120d","detail":"full","id":"property.keyframes.list","idempotency":"idempotent","inputSchema":{"additionalProperties":false,"properties":{"limit":{"maximum":25,"minimum":1,"type":"integer"},"offset":{"$ref":"aegp-rpc.schema.json#/$defs/pageOffset"}},"required":["offset","limit"],"type":"object"},"mutability":"read-only","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/layerPropertyKeyframesListValue"},"risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read property.keyframes.list.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"4635375dc6c905a212dede8a37ef623c0f9d948eb9e913c84625d099aa8ffaa7","detail":"full","id":"property.value.set","idempotency":"idempotency-key","inputSchema":{"additionalProperties":false,"properties":{"value":{"$ref":"aegp-rpc.schema.json#/$defs/layerPropertyPrimitiveValue"}},"required":["value"],"type":"object"},"mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/layerPropertySetInvokeResult"},"risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.value.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"e5572da81eb8aae1ab8f5a1eb7c5c90c45db2ba071f45203d2f4420a98e95631","detail":"full","id":"property.keyframe.details.read","idempotency":"idempotent","inputSchema":{"additionalProperties":false,"properties":{"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"}},"required":["time"],"type":"object"},"mutability":"read-only","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeDetailsValue"},"risk":"read","schemaVersion":1,"sideEffectSummary":"Reads After Effects state without changing it.","summary":"Read property.keyframe.details.read.","undo":"not-applicable","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"7fb5dba2374ae2ad9caf4c82d348264dde31d7d2f78090ed55655e2256676585","detail":"full","id":"property.keyframe.add","idempotency":"idempotency-key","inputSchema":{"additionalProperties":false,"properties":{"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"},"value":{"$ref":"aegp-rpc.schema.json#/$defs/layerPropertyPrimitiveValue"}},"required":["time","value"],"type":"object"},"mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeAddInvokeResult"},"risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.keyframe.add.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"70f43eace3d3173f68cf2e3d76225e25c974ea5851ca97759656373d903a7e83","detail":"full","id":"property.keyframe.value.set","idempotency":"idempotency-key","inputSchema":{"additionalProperties":false,"properties":{"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"},"value":{"$ref":"aegp-rpc.schema.json#/$defs/layerPropertyPrimitiveValue"}},"required":["time","value"],"type":"object"},"mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeValueSetInvokeResult"},"risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.keyframe.value.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"e52cb0c2bda4e5c40f2d3b5fd70a214b4715034381ea7eb67bd5a53f658a7e2b","detail":"full","id":"property.keyframe.interpolation.set","idempotency":"idempotency-key","inputSchema":{"additionalProperties":false,"properties":{"inInterpolation":{"enum":["linear","bezier","hold"]},"outInterpolation":{"enum":["linear","bezier","hold"]},"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"}},"required":["time","inInterpolation","outInterpolation"],"type":"object"},"mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeInterpolationSetInvokeResult"},"risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.keyframe.interpolation.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"d9592296b2747a20f52dc19a4f11fd79382cb1805e3992bfd3f97981fd95e726","detail":"full","id":"property.keyframe.temporalEase.set","idempotency":"idempotency-key","inputSchema":{"additionalProperties":false,"properties":{"dimensions":{"items":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeEaseDimension"},"maxItems":4,"minItems":1,"type":"array"},"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"}},"required":["time","dimensions"],"type":"object"},"mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTemporalEaseSetInvokeResult"},"risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.keyframe.temporalEase.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"fcdf78a9cab89688f334c7cd897d0d55fa225073fc90bbe6c7f69f8253502d5e","detail":"full","id":"property.keyframe.behavior.set","idempotency":"idempotency-key","inputSchema":{"additionalProperties":false,"properties":{"behavior":{"enum":["temporal-continuous","temporal-auto-bezier","spatial-continuous","spatial-auto-bezier","roving"]},"enabled":{"type":"boolean"},"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"}},"required":["time","behavior","enabled"],"type":"object"},"mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeBehaviorSetInvokeResult"},"risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.keyframe.behavior.set.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
    R"NATIVEEXEC({"cancellation":"before-dispatch","compatibility":{"intendedPlatforms":["macos-arm64","windows-x64"],"status":"unverified"},"contractDigest":"3c55651f88aa696be0fe825113c31bd6066cb23b0152940a1b7ac486fc638114","detail":"full","id":"property.keyframe.delete","idempotency":"idempotency-key","inputSchema":{"additionalProperties":false,"properties":{"time":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeTimeInput"}},"required":["time"],"type":"object"},"mutability":"mutating","preconditions":["AEGP_StreamSuite5 must be available."],"requiredSuite":"AEGP_StreamSuite5","resultSchema":{"$ref":"aegp-rpc.schema.json#/$defs/keyframeDeleteInvokeResult"},"risk":"write","schemaVersion":1,"sideEffectSummary":"Changes After Effects state within one native program Undo group.","summary":"Write property.keyframe.delete.","undo":"ae-undo-group","valueKind":"Json","version":1})NATIVEEXEC",
}};

inline std::span<const NativePrimitiveDescriptor> native_primitive_registry() {
  return kNativePrimitiveRegistry;
}

inline const NativePrimitiveDescriptor* find_native_primitive(std::string_view id) {
  for (const auto& descriptor : kNativePrimitiveRegistry) {
    if (descriptor.id == id) return &descriptor;
  }
  return nullptr;
}

}  // namespace aemcp::native
